# Generated by Django 4.0.3 on 2022-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='avatar',
        ),
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(null=True, upload_to='comment'),
        ),
    ]
