# Generated by Django 4.0.3 on 2022-04-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default=None, upload_to='post', null=True),
            preserve_default=False,
        ),
    ]
