# Generated by Django 4.0.3 on 2022-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='post'),
        ),
    ]
